apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/oleg/all-qa/all-infra/k8s/selenium/config.toml
        containerPath: /opt/bin/config.toml
