apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: node-docker
  name: node-docker
  namespace: all-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node-docker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: node-docker
    spec:
      containers:
      - env:
        - name: SE_EVENT_BUS_HOST
          value: selenium-hub
        - name: SE_EVENT_BUS_PUBLISH_PORT
          value: "4442"
        - name: SE_EVENT_BUS_SUBSCRIBE_PORT
          value: "4443"
        image: selenium/node-docker:4.2.2
        imagePullPolicy: ""
        name: node-docker
        resources: {}
        volumeMounts:
        - name: node-docker-claim0
          mountPath: /opt/bin/config.toml
      restartPolicy: Always
      volumes:
      - name: node-docker-claim0
        persistentVolumeClaim:
          claimName: node-docker-claim0
status: {}
