apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-docker-persistentvolume0
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: "/home/oleg/all-qa/all-infra/k8s/selenium/config.toml"
