apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: selenium-hub
  name: selenium-hub
  namespace: all-infra
spec:
  ports:
  - name: "4442"
    port: 4442
    targetPort: 4442
  - name: "4443"
    port: 4443
    targetPort: 4443
  - name: "4444"
    port: 4444
    targetPort: 4444
  selector:
    io.kompose.service: selenium-hub
status:
  loadBalancer: {}
