apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: selenium-hub
  name: selenium-hub
  namespace: all-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: selenium-hub
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: selenium-hub
    spec:
      containers:
      - name: ubuntu     
        image: ubuntu:latest
        imagePullPolicy: "Always"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 4442
        - containerPort: 4443
        - containerPort: 4444
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
